---
title: "emodis-1"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{emodis-1}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Loading Packages

```{r setup, warning=FALSE, message=FALSE}
library(emodis)
library(sf)
library(CAST)
library(raster)
library(ggplot2)
library(ggpubr)
```

## Sampling Designs

```{r create-sample-plots}
samples_root <- system.file("extdata", "samples", package="emodis")
# create a raster with the response variable
print(system.file("extdata", "data", "agb_resampled.tif", package="emodis"))
agb <- raster(system.file("extdata", "data", "agb_resampled.tif", package="emodis"))
sample_plots <- lapply(c("simpleRandom", "regular", 
                         "clusterMedium", "clusterStrong", "clusterGapped"), function(dir) {
  # pick a random sampling realization
  r <- floor(runif(1, 1, 100))
  print(paste0(dir, ": plotting sampling design # ", r))
  # load the ???_coords.Rdata file holding its coordinates
  samp_name <- paste0(samples_root, "/", dir, "/", sprintf("%03d", r), "_coords", ".Rdata")
  load(samp_name)
  # make sure it's an sf of the same CRS
  if(class(pts)[1] != "sf") {
    sample_df <- as.data.frame(pts)
    sample_sf <- st_as_sf(sample_df, coords = c("x", "y"))
    # this is a bit dirty but the pts object definitely contains data in that CRS
    st_crs(sample_sf) <- st_crs(agb) # EPSG:3035
  } else {
    sample_sf <- pts
  }
  
  # make the raster into a df for ggplot
  agb_df <- as.data.frame(agb, xy=TRUE)
  
  # create a plot per sampling
  m1 <- ggplot() + 
    geom_raster(data=agb_df, aes(x=x, y=y, fill=agb_resampled)) + 
    geom_sf(data=sample_sf, shape = 2, size = 0.1) + 
    theme_light() +
    scale_fill_gradientn(colours=terrain.colors(10), na.value="transparent") +
    ggtitle(dir)
  
  return(m1)
})
```

```{r plot-sample-plots, fig.width=7, fig.height=5}
ggarrange(plotlist=sample_plots, ncol=3, nrow=2, common.legend = T)
```

## Validation Results

```{r analysis-light}
data_root <- system.file("extdata", package="emodis")
results_root <- file.path(data_root, "CVresults")

df <- data.frame(method=character(), sample=character(), iteration=numeric(), 
                 RMSE=numeric(), RMSE_val=numeric(), s2s_s2p=numeric(), 
                 s2s_cv=numeric(), s2p_cv=numeric())

for (method in c("random", "spatial", "nndm")) {
  nr_of_files <- length(list.files(file.path(results_root, method), glob2rx("AGB_*.Rdata")))
  for (smpl in c("simpleRandom", "regular", "clusterMedium", "clusterStrong", "clusterGapped")) {
    for (iteration in 1:10){ # 1:nr_of_files) {
      # print(paste(method, smpl, iteration, "starting"))
      
      # define file names
      filename <- paste0("AGB_", smpl, sprintf("%03d", iteration), ".Rdata")
      result_file <- file.path(results_root, method, filename)
      exhaustive_file <- file.path(results_root, "exhaustive", filename)

      # define coordinate file
      coordsname <- paste0(sprintf("%03d", iteration), "_coords.Rdata")
      coords_file <- file.path(samples_root, smpl, coordsname)

      if (!file.exists(exhaustive_file)) next
      if (!file.exists(result_file)) next
      if (!file.exists(coords_file)) next
      
      # load the validation error of the specific sampling design
      load(exhaustive_file) # this loads "RMSE"
      RMSE_val <- RMSE
      
      # load the error estimated via CV
      load(result_file) # this loads and overwrites RMSE
      if(length(RMSE) > 1) {RMSE <- mean(RMSE)}
      
      df <- rbind(df, c(method, smpl, iteration, RMSE, RMSE_val, 0, 0, 0))
    }
  }
}

names(df) <- c("method", "sample", "iteration", "RMSE", "RMSE_val", "s2s_s2p", "s2s_cv", "s2p_cv")
```

```{r, fig.width=7, fig.height=5}
df$RMSE <- as.numeric(df$RMSE)
df$RMSE_val <- as.numeric(df$RMSE_val)
df$method <- factor(df$method, levels = c('random','spatial','nndm'),ordered = TRUE)
df$sample <- factor(df$sample, levels = c('simpleRandom','regular','clusterMedium',
                                          'clusterStrong', 'clusterGapped'),ordered = TRUE)

df$r_RMSE <- 100 * (df$RMSE - df$RMSE_val) / df$RMSE_val

ggplot(data=df, aes(x=method, y=r_RMSE, color=sample)) +
  geom_boxplot()
```
## `plot_geodist` Examples

